env:
  TG_BOT_TOKEN: "ENCRYPTED[4326415f4acc435fb4c3849c16d2053e5a6b2d28b53d2618e87f31de166791def1867e131289bcf2b6ad61cb464a2fad]"
  TG_CHAT_ID: "ENCRYPTED[44a602fbf52c71e2b429bea0b1622c05a6d7643b34de8aec767c4d94bc264e09a787a4b307a7717fdea6b07986c4fbd2]"
  RCLONE_CONF: "ENCRYPTED[d289404fb496bb8daba414e9fcc2a2a720094eeb2e3e7e298e53cd059a3053c243248808bcdb01186b29023f692e4912]"
  GH_TOKEN: "ENCRYPTED[c77743ba18cc41a9032db101e043b4c277873fb7f115368f50bf6feeab34486928f7051d39fa1d2f6ada8a69f2ee79c6]"
  GH_USERNAME: "ENCRYPTED[f2ca4e71130edd4edb7497f02e2af984b46e06e7875b836900f8ce81a6462cc6dec53fcb63c761b80632c078b1cb2148]"
  BUILD_HOSTNAME: "ENCRYPTED[45e06def190d09b325d48e34895b4c9c7705dc4dfd4f0dadea6c51f429e303ba794d977bc506d1256de4781f03f4d121]"

task:
  name: Build LineageOS ROM
  timeout_in: 120m
  container:
    image: inok2341/anu:latest
    cpu: 8
    memory: 32G
    greedy: true

  # 1. Install required tools
  install_script:
    - sudo apt-get update && sudo apt-get install -y rclone git-lfs python3
    - pwd
    - ls -la

  # 2. Setup environment credentials and initialize Repo
  setup_stage_script:
    - python3 build_rom.py setup

  # 3. Sync the main source code
  sync_stage_script:
    - python3 build_rom.py sync

  # 4. Clone X00TD device specific trees
  clone_stage_script:
    - python3 build_rom.py clone

  # 5. Start the core compilation process
  build_stage_script:
    - python3 build_rom.py build

  # 6. Check MD5 and upload compiled ROM to Google Drive
  upload_stage_script:
    - python3 build_rom.py upload
